<?php
return [
    'agenda' => [
        1 => [
            ['time_start' => '08:15', 'time_end' => '10:15', 'activity' => 'Closed Session (For Members Only)'],
            ['time_start' => '10:15', 'time_end' => '10:30', 'activity' => 'Refreshments'],
            ['time_start' => '10:30', 'time_end' => '11:00', 'activity' => 'Keynote Address', 'speaker' => 'Prof. Emeritus Dato Dr. Ibrahim Komoo'],
            ['time_start' => '11:00', 'time_end' => '11:30', 'activity' => 'Plenary: Main Working Paper', 'speaker' => 'Sabah Forestry Department'],
            ['time_start' => '11:30', 'time_end' => '12:00', 'activity' => 'Plenary: Main Working Paper', 'speaker' => 'Forestry Department of Peninsular Malaysia'],
            ['time_start' => '12:00', 'time_end' => '12:30', 'activity' => 'Plenary: Main Working Paper', 'speaker' => 'Forest Department Sarawak'],
            ['time_start' => '12:30', 'time_end' => '13:45', 'activity' => 'Lunch'],
            ['time_start' => '13:45', 'time_end' => '14:00', 'activity' => 'Subtheme 1: Policy and Governance — Session Commencement'],
            ['time_start' => '14:00', 'time_end' => '14:20', 'activity' => 'Paper 1: Digital Governance in Forestry: Enhancing STLVS Integrity and Revenue Efficiency', 'speaker' => 'Semilan Ripot et al., Forest Department Sarawak'],
            ['time_start' => '14:20', 'time_end' => '14:40', 'activity' => 'Paper 2: Unlocking Natural Capital: Sabah\'s Policy Frameworks for a Forest-Based Green Economy', 'speaker' => 'Indra P. H. Sunjoto et al., Sabah Forestry Department'],
            ['time_start' => '14:40', 'time_end' => '15:00', 'activity' => 'Paper 3: Penetapan Pendengaran Awam Bagi Pewartaan Keluar Hutan Simpanan Kekal', 'speaker' => 'Zarin R. et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '15:00', 'time_end' => '15:20', 'activity' => 'Paper 4: Science-Based Forest Policy: Integrating Dipterocarp Population Assessment into Sarawak\'s CITES Framework', 'speaker' => 'Vilma Bodos, Forest Department Sarawak'],
            ['time_start' => '15:20', 'time_end' => '15:30', 'activity' => 'Question and Answer Session'],
            ['time_start' => '15:30', 'time_end' => '23:59', 'activity' => 'Refreshments & End of Day 1'],
        ],
        2 => [
            ['time_start' => '08:30', 'time_end' => '08:40', 'activity' => 'Subtheme 2: Nature-Based Adaptation and Resolution — Session Commencement'],
            ['time_start' => '08:40', 'time_end' => '09:00', 'activity' => 'Paper 1: Pengalaman dan Cabaran Pengurusan Kebakaran Hutan Paya Gambut di Selangor', 'speaker' => 'Azhar Ahmad et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '09:00', 'time_end' => '09:20', 'activity' => 'Paper 2: Estimating Aboveground Forest Carbon Density through LiDAR and Geospatial Remote Sensing in Sarawak', 'speaker' => 'Dr Malcom anak Demies, Forest Department Sarawak'],
            ['time_start' => '09:20', 'time_end' => '09:40', 'activity' => 'Paper 3: Ecological Dynamics of Tropical Highland Peat Ecosystems', 'speaker' => 'Zainuddin Jamaluddin et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '09:40', 'time_end' => '10:00', 'activity' => 'Paper 4: Nature, Climate, and Economy: Sabah\'s Pathway Through Nature-Based Solutions', 'speaker' => 'Rosila Anthony et al., Sabah Forestry Department'],
            ['time_start' => '10:00', 'time_end' => '10:10', 'activity' => 'Question and Answer Session'],
            ['time_start' => '10:10', 'time_end' => '10:30', 'activity' => 'Refreshments'],
            ['time_start' => '10:30', 'time_end' => '10:40', 'activity' => 'Subtheme 3: Partnership and Collaboration — Session Commencement'],
            ['time_start' => '10:40', 'time_end' => '11:00', 'activity' => 'Paper 1: Sabah Timber Legality Assurance System Plus (TLAS+)', 'speaker' => 'Mijol R. M. et al., Sabah Forestry Department'],
            ['time_start' => '11:00', 'time_end' => '11:20', 'activity' => 'Paper 2: Operasi Penguatkuasaan Bersepadu Jabatan Perhutanan Semenanjung Malaysia', 'speaker' => 'Gana R. K. et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '11:20', 'time_end' => '11:40', 'activity' => 'Paper 3: Digitalizing Conservation Governance: HOBS Cross-Agency Project Management System', 'speaker' => 'Meliza Binti Mohd Rizan, Forest Department Sarawak'],
            ['time_start' => '11:40', 'time_end' => '12:00', 'activity' => 'Paper 4', 'speaker' => 'Professor Ts. Dr. Faisal Ali bin Anwarali Khan, Unimas'],
            ['time_start' => '12:00', 'time_end' => '12:10', 'activity' => 'Question and Answer Session'],
            ['time_start' => '12:10', 'time_end' => '13:30', 'activity' => 'Lunch'],
            ['time_start' => '13:30', 'time_end' => '13:40', 'activity' => 'Subtheme 4: Biodiversity Research and Conservation — Session Commencement'],
            ['time_start' => '13:40', 'time_end' => '14:00', 'activity' => 'Paper 1: Ekspedisi Saintifik Kepelbagaian Biologi Hutan: Pencapaian dan Hala Tuju', 'speaker' => 'Siti Khatijah Othman et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '14:00', 'time_end' => '14:20', 'activity' => 'Paper 2: Developing a Forest Reference Level Monitoring System in Sabah', 'speaker' => 'Reuben Nilus et al., Sabah Forestry Department'],
            ['time_start' => '14:20', 'time_end' => '14:40', 'activity' => 'Paper 3: The Use of UAV-based LiDAR for Forest Volume Modeling in Sarawak', 'speaker' => 'Bibian Anak Micheal Diway, Forest Department Sarawak'],
            ['time_start' => '14:40', 'time_end' => '15:00', 'activity' => 'Paper 4', 'speaker' => 'Sarawak Forestry Corporation'],
            ['time_start' => '15:00', 'time_end' => '15:10', 'activity' => 'Question and Answer Session'],
            ['time_start' => '15:10', 'time_end' => '15:20', 'activity' => 'Refreshments'],
            ['time_start' => '15:20', 'time_end' => '15:30', 'activity' => 'Subtheme 5: Forest Plantation and Restoration — Session Commencement'],
            ['time_start' => '15:30', 'time_end' => '15:50', 'activity' => 'Paper 1: Forest Restoration and Rehabilitation: Experience and Insights', 'speaker' => 'Rohanie Bohan & Zarina Shelbi, Forest Department Sarawak'],
            ['time_start' => '15:50', 'time_end' => '16:10', 'activity' => 'Paper 2: Forest Landscape Restoration Approaches to Strengthen Forest Sustainability in Peninsular Malaysia', 'speaker' => 'M. Hafni & A. Richard, Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '16:10', 'time_end' => '16:30', 'activity' => 'Paper 3: Shifting Dependency on Natural Forests to Forest Plantations', 'speaker' => 'Heidi Henry William et al., Sabah Forestry Department'],
            ['time_start' => '16:30', 'time_end' => '16:50', 'activity' => 'Paper 4: Transforming Industrial Forest Plantations through R&D and Certification', 'speaker' => 'Roger Tami, Samling Reforestation (Bintulu) Sdn. Bhd.'],
            ['time_start' => '16:50', 'time_end' => '17:00', 'activity' => 'Question and Answer Session'],
            ['time_start' => '17:00', 'time_end' => '23:59', 'activity' => 'End of Day 2'],
        ],
        3 => [
            ['time_start' => '08:30', 'time_end' => '08:40', 'activity' => 'Subtheme 6: Social Forestry & Ecotourism — Session Commencement'],
            ['time_start' => '08:40', 'time_end' => '09:00', 'activity' => 'Paper 1: Seridang Folia: A Community\'s Journey with Tongkat Ali in the Heart of Borneo', 'speaker' => 'Suliman Bin Haji Jamahari, Forest Department Sarawak'],
            ['time_start' => '09:00', 'time_end' => '09:20', 'activity' => 'Paper 2: Beyond Conservation: Community Participation as a Driver of Green Economy in Sabah', 'speaker' => 'E. B. Johnlee et al., Sabah Forestry Department'],
            ['time_start' => '09:20', 'time_end' => '09:40', 'activity' => 'Paper 3: Pengurusan Kawasan Pendakian Di Dalam Hutan Simpanan Kekal Di Semenanjung Malaysia', 'speaker' => 'Nor Zaidi Jusoh et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '09:40', 'time_end' => '10:00', 'activity' => 'Paper 4: Community-based Tourism and its Contribution to Local Economies: Insights from Peros', 'speaker' => 'Madeline George Pau et al., Forest Department Sarawak'],
            ['time_start' => '10:00', 'time_end' => '10:10', 'activity' => 'Question and Answer Session'],
            ['time_start' => '10:10', 'time_end' => '11:00', 'activity' => 'Refreshments'],
            ['time_start' => '11:00', 'time_end' => '11:05', 'activity' => 'Session Commencement'],
            ['time_start' => '11:05', 'time_end' => '12:30', 'activity' => 'Conference Resolution Presentation and Adoption'],
            ['time_start' => '12:30', 'time_end' => '13:30', 'activity' => 'Closing Ceremony', 'speaker' => 'Datu Haji Abdullah Bin Julaihi, Permanent Secretary'],
            ['time_start' => '13:30', 'time_end' => '23:59', 'activity' => 'Lunch and End of Conference'],
        ],
    ]
];