<?php
return [
    'agenda' => [
        1 => [
            ['time_start' => '08:15', 'time_end' => '10:15', 'activity' => 'Opening Formalities', 'items' => [
                'Appointment of the Conference\'s Chairman by previous Chairman',
                'Introduction remarks by respective Heads of Departments',
                'Appointment of Conference Officials',
                'Reporting of the 20th Malaysian Forestry Conference Resolutions',
                'Amendment to the Standing Orders of Malaysian Forestry Conference, if any',
            ]],
            ['time_start' => '10:15', 'time_end' => '10:30', 'activity' => 'Refreshments'],
            ['time_start' => null, 'time_end' => null, 'activity' => 'Plenary Session: Keynote Address and Main Working Paper', 'type' => 'header'],
            ['time_start' => '10:30', 'time_end' => '11:00', 'activity' => 'Keynote Address: Protected Areas, Eco-Forest Parks, and Geoparks: Drivers of Green Economy and Sustainability in Malaysian Forestry', 'speaker' => 'Prof. Emeritus Dato Dr. Ibrahim Komoo'],
            ['time_start' => '11:00', 'time_end' => '11:30', 'activity' => 'Main Working Paper 1', 'speaker' => 'Sabah Forestry Department'],
            ['time_start' => '11:30', 'time_end' => '12:00', 'activity' => 'Main Working Paper 2', 'speaker' => 'Forestry Department of Peninsular Malaysia'],
            ['time_start' => '12:00', 'time_end' => '12:30', 'activity' => 'Main Working Paper 3', 'speaker' => 'Forest Department Sarawak'],
            ['time_start' => '12:30', 'time_end' => '13:45', 'activity' => 'Lunch'],
            ['time_start' => null, 'time_end' => null, 'activity' => 'Subtheme 1: Policy and Governance', 'chairman' => 'Tuan Muhamad Bin Abdullah (Jabatan Perhutanan Semenanjung Malaysia)', 'type' => 'header'],
            ['time_start' => '13:45', 'time_end' => '14:00', 'activity' => 'Session Commencement'],
            ['time_start' => '14:00', 'time_end' => '14:20', 'activity' => 'Paper 1: Digital Governance in Forestry: Enhancing STLVS Integrity and Revenue Efficiency as a Catalyst for Sarawak\'s Green Economy', 'speaker' => 'Hasnaliza B.A. et al., Forest Department Sarawak'],
            ['time_start' => '14:20', 'time_end' => '14:40', 'activity' => 'Paper 2: Unlocking Natural Capital: Sabah\'s Policy Frameworks for a Forest-Based Green Economy', 'speaker' => 'Indra P. H. Sunjoto et al., Sabah Forestry Department'],
            ['time_start' => '14:40', 'time_end' => '15:00', 'activity' => 'Paper 3: Penetapan Pendengaran Awam (Public Hearing) Bagi Pewartaan Keluar Hutan Simpanan Kekal (HSK) Di Semenanjung Malaysia', 'speaker' => 'Zarin R. et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '15:00', 'time_end' => '15:20', 'activity' => 'Paper 4: Science-Based Forest Policy in Action: Integrating Dipterocarp Population Assessment into Sarawak\'s Efforts on CITES and the Sustainable Timber Framework', 'speaker' => 'Vilma Bodos et al., Forest Department Sarawak'],
            ['time_start' => '15:20', 'time_end' => '15:30', 'activity' => 'Question and Answer Session'],
            ['time_start' => '15:30', 'time_end' => null, 'activity' => 'Refreshments & End of Day 1'],
        ],
        2 => [
            ['time_start' => null, 'time_end' => null, 'activity' => 'Subtheme 2: Nature-Based Adaptation and Solution', 'chairman' => 'Tuan Haji Mohd. Ridzuwan Bin Endor (Jabatan Perhutanan Semenanjung Malaysia)', 'type' => 'header'],
            ['time_start' => '08:30', 'time_end' => '08:40', 'activity' => 'Session Commencement'],
            ['time_start' => '08:40', 'time_end' => '09:00', 'activity' => 'Paper 5: Pengalaman Dan Cabaran Pengurusan Kebakaran Hutan Paya Gambut Di Selangor', 'speaker' => 'Debora Belawan et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '09:00', 'time_end' => '09:20', 'activity' => 'Paper 6: Estimating Aboveground Forest Carbon Density through LiDAR and Geospatial Remote Sensing in Sarawak', 'speaker' => 'Dr Malcom anak Demies et al., Forest Department Sarawak'],
            ['time_start' => '09:20', 'time_end' => '09:40', 'activity' => 'Paper 7: A Review: Ecological Dynamics of Tropical Highland Peat Ecosystems', 'speaker' => 'Iqtie Qamar Laila Mohd Gani et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '09:40', 'time_end' => '10:00', 'activity' => 'Paper 8: Nature, Climate, and Economy: Sabah\'s Pathway Through Nature-Based Solutions', 'speaker' => 'Rosila Anthony et al., Sabah Forestry Department'],
            ['time_start' => '10:00', 'time_end' => '10:10', 'activity' => 'Question and Answer Session'],
            ['time_start' => '10:10', 'time_end' => '10:30', 'activity' => 'Refreshments'],
            ['time_start' => null, 'time_end' => null, 'activity' => 'Subtheme 3: Partnership and Collaboration', 'chairman' => 'Tuan Indra Puwandita Bin Herry Sunjoto (Sabah Forestry Department)', 'type' => 'header'],
            ['time_start' => '10:30', 'time_end' => '10:40', 'activity' => 'Session Commencement'],
            ['time_start' => '10:40', 'time_end' => '11:00', 'activity' => 'Paper 9: Sabah Timber Legality Assurance System Plus (TLAS+): Advancing Timber Legality through International Collaboration', 'speaker' => 'Mijol R. M et al., Sabah Forestry Department'],
            ['time_start' => '11:00', 'time_end' => '11:20', 'activity' => 'Paper 10: Operasi Penguatkuasaan Bersepadu Jabatan Perhutanan Semenanjung Malaysia', 'speaker' => 'Gana R.K et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '11:20', 'time_end' => '11:40', 'activity' => 'Paper 11: Digitalizing Conservation Governance: [HOBS] A Cross-Agency Project Management System for the Heart of Borneo in Sarawak', 'speaker' => 'Meliza Binti Mohd Rizan et al., Forest Department Sarawak'],
            ['time_start' => '11:40', 'time_end' => '12:00', 'activity' => 'Paper 12: Small Mammal Diversity in Borneo: Insights from Historical Records and Collaborative Biodiversity Assessments', 'speaker' => 'Professor Ts. Dr. Faisal Ali bin Anwarali Khan et al., Unimas'],
            ['time_start' => '12:00', 'time_end' => '12:10', 'activity' => 'Question and Answer Session'],
            ['time_start' => '12:10', 'time_end' => '13:30', 'activity' => 'Lunch'],
            ['time_start' => null, 'time_end' => null, 'activity' => 'Subtheme 4: Biodiversity Research and Conservation', 'chairman' => 'Arthur Chung Yaw Chyang (Sabah Forestry Department)', 'type' => 'header'],
            ['time_start' => '13:30', 'time_end' => '13:40', 'activity' => 'Session Commencement'],
            ['time_start' => '13:40', 'time_end' => '14:00', 'activity' => 'Paper 13: Ekspedisi Saintifik Kepelbagaian Biologi Hutan: Pencapaian dan Hala Tuju', 'speaker' => 'Siti Khatijah Othman et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '14:00', 'time_end' => '14:20', 'activity' => 'Paper 14: Developing a Forest Reference Level Monitoring System in Sabah: Integrating Field Biometrics and Remote Sensing for Biodiversity Conservation and Sustainable Forest Management', 'speaker' => 'Reuben Nilus et al., Sabah Forestry Department'],
            ['time_start' => '14:20', 'time_end' => '14:40', 'activity' => 'Paper 15: The use of UAV-based LiDAR for Forest Volume Modeling in Sarawak', 'speaker' => 'Bibian Diway et al., Forest Department Sarawak'],
            ['time_start' => '14:40', 'time_end' => '15:00', 'activity' => 'Paper 16: An Overview of Orangutan Conservation in Sarawak for the Next Decade', 'speaker' => 'Aliana Binti Affendi et al., Sarawak Forestry Corporation'],
            ['time_start' => '15:00', 'time_end' => '15:20', 'activity' => 'Paper 17: Vascular Plant Diversity and Conservation Importance of the Ultramafic Forests of Meliau Range, Central Sabah', 'speaker' => 'Jonathan J. Lucas et al., Sabah Forestry Department'],
            ['time_start' => '15:20', 'time_end' => '15:30', 'activity' => 'Question and Answer Session'],
            ['time_start' => '15:30', 'time_end' => '15:40', 'activity' => 'Refreshments'],
            ['time_start' => null, 'time_end' => null, 'activity' => 'Subtheme 5: Forest Plantation and Restoration', 'chairman' => 'Dr. Affendi bin Suhaili (Forest Department Sarawak)', 'type' => 'header'],
            ['time_start' => '15:40', 'time_end' => '16:00', 'activity' => 'Session Commencement'],
            ['time_start' => '16:00', 'time_end' => '16:20', 'activity' => 'Paper 18: Forest Restoration and Rehabilitation: Experiences and Insights', 'speaker' => 'Zarina, S. et al., Forest Department Sarawak'],
            ['time_start' => '16:20', 'time_end' => '16:30', 'activity' => 'Paper 19: Forest Landscape Restoration Approaches to Strengthen Forest Sustainability In Peninsular Malaysia', 'speaker' => 'M. Hafni et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '16:30', 'time_end' => '16:50', 'activity' => 'Paper 20: Shifting Dependency on Natural Forests to Forest Plantations in Support of Forest Landscape Sustainability', 'speaker' => 'Heidi Henry William et al., Sabah Forestry Department'],
            ['time_start' => '16:50', 'time_end' => '17:10', 'activity' => 'Paper 21: Transforming Industrial Forest Plantations through R&D and Certification: Samling\'s Experience In Sarawak, Malaysia', 'speaker' => 'Roger Tami et al., Samling Reforestation (Bintulu) Sdn. Bhd.'],
            ['time_start' => '17:10', 'time_end' => '17:20', 'activity' => 'Question and Answer Session'],
            ['time_start' => '17:20', 'time_end' => null, 'activity' => 'End of Day 2'],
        ],
        3 => [
            ['time_start' => null, 'time_end' => null, 'activity' => 'Subtheme 6: Social Forestry & Ecotourism', 'chairman' => 'Tuan Haji Happysupina Bin Sait (Forest Department Sarawak)', 'type' => 'header'],
            ['time_start' => '08:30', 'time_end' => '08:40', 'activity' => 'Session Commencement'],
            ['time_start' => '08:40', 'time_end' => '09:00', 'activity' => 'Paper 22: Seridan Folia: A Community\'s Journey with Tongkat Ali in the Heart of Borneo', 'speaker' => 'Suliman Bin Haji Jamahari et al., Forest Department Sarawak'],
            ['time_start' => '09:00', 'time_end' => '09:20', 'activity' => 'Paper 23: Beyond Conservation: Community Participation as a Driver of Green Economy in Sabah\'s Forest Landscapes', 'speaker' => 'E.B. Johnlee et al., Sabah Forestry Department'],
            ['time_start' => '09:20', 'time_end' => '09:40', 'activity' => 'Paper 24: Pengurusan Kawasan Pendakian Di Dalam Hutan Simpanan Kekal Di Semenanjung Malaysia', 'speaker' => 'Reanee Lee et al., Jabatan Perhutanan Semenanjung Malaysia'],
            ['time_start' => '09:40', 'time_end' => '10:00', 'activity' => 'Paper 25: Community-based Tourism and its Contribution to Local Economies: Insights from Peros', 'speaker' => 'Madeline George Pau et al., Forest Department Sarawak'],
            ['time_start' => '10:00', 'time_end' => '10:10', 'activity' => 'Question and Answer Session'],
            ['time_start' => '10:10', 'time_end' => '10:25', 'activity' => 'Refreshments'],
            ['time_start' => null, 'time_end' => null, 'activity' => 'Closed Sessions (For Members Only)', 'type' => 'header'],
            ['time_start' => '10:25', 'time_end' => '10:30', 'activity' => 'Session Commencement'],
            ['time_start' => '10:30', 'time_end' => '12:30', 'activity' => 'Conference Resolution Presentation and Adoption'],
            ['time_start' => null, 'time_end' => null, 'activity' => 'Closing Ceremony', 'type' => 'header'],
            ['time_start' => '12:30', 'time_end' => '13:30', 'activity' => 'Closing Ceremony', 'items' => [
                'Arrival of Permanent Secretary, Ministry of Natural Resources and Urban Development, Datu Haji Abdullah Bin Julaihi',
                'Negaraku and Ibu Pertiwiku',
                'Recital of Doa',
                'Closing Address by Permanent Secretary',
                'Photo Session',
            ]],
            ['time_start' => '13:30', 'time_end' => null, 'activity' => 'Lunch and End of Conference'],
        ],
    ]
];